nome = str(input('Digite seu nome completo: ')).strip()
print("Analisando seu nome...")
print(f'Seu nome em maiusculo é: {nome.upper()}')
print(f'Seu nome em minusculo é: {nome.lower()}')
print(f'Seu nome ao todo tem {len(nome)-nome.count(' ')} letras')
print(f'Seu primeiro nome é {nome.split()[0]} e tem {len(nome.split()[0])} letras')
